<?php
/*
 * telegraf configuration for the IXP Manager Graphite grapher backend (WRITE side).
 *
 * GENERATED by `php artisan grapher:generate-telegraf-config` — DO NOT EDIT BY HAND.
 * Regenerate (e.g. from cron) whenever switches change.
 *
 * telegraf walks the per-port IF-MIB counters (all ports) on every active,
 * poll-enabled switch and pushes the RAW counters to carbon under:
 *
 *     <?=$this->prefix?>.switch.<switchId>.port.<ifIndex>.<category>.<direction>
 *
 * The metric name is assembled in two steps:
 *   1. a starlark processor rebuilds the measurement from the per-switch `swid`
 *      tag (the switch DB id) and the walked `index` tag (ifIndex):
 *          switch.<swid>.port.<index>
 *   2. the graphite serializer template "measurement.field" appends the field
 *      name (e.g. bits.in) → switch.<id>.port.<ifIndex>.<cat>.<dir>, prefixed.
 *
 * Why starlark and not a tag placed directly in the template: the graphite
 * serializer sanitizes dots in TAG VALUES to underscores (verified), but keeps
 * dots in the measurement and field names. So the dotted path must live in the
 * measurement, not a tag. This MUST stay byte-identical to
 * \IXP\Utils\Grapher\Graphite::metricName() (the read side).
 *
 * NOTE: contains SNMP community strings in plaintext — store with mode 0600.
 */
?>
[agent]
  interval        = "<?=$this->interval?>"
  round_interval  = true
  omit_hostname   = true
  flush_interval  = "10s"

[[outputs.graphite]]
  servers            = ["<?=$this->carbonHost?>:<?=$this->carbonPort?>"]
  prefix             = "<?=$this->prefix?>"
  template           = "measurement.field"
  graphite_separator = "."

# Rebuild the measurement into the metric path from the switch id + ifIndex tags.
[[processors.starlark]]
  source = '''
def apply(metric):
    swid = metric.tags.get("swid")
    idx  = metric.tags.get("index")
    if swid == None or idx == None:
        return metric
    metric.name = "switch." + swid + ".port." + idx
    return metric
'''

<?php foreach( $this->switches as $s ):
    // TOML basic-string escape for the community: backslash then double-quote
    $community = str_replace( [ '\\', '"' ], [ '\\\\', '\\"' ], (string) $s->snmppasswd );
?>
# ---- switch <?=$s->id?>: <?=$s->name ?? $s->hostname?> ----
[[inputs.snmp]]
  agents    = ["<?=$s->hostname?>"]
  version   = 2
  community = "<?=$community?>"
  timeout   = "5s"
  retries   = 1
  [inputs.snmp.tags]
    swid = "<?=(int) $s->id?>"
  [[inputs.snmp.table]]
    name         = "<?=$this->prefix?>"
    index_as_tag = true
<?php foreach( $this->categories as $cat ): ?>
    [[inputs.snmp.table.field]]
      oid  = "<?= \IXP\Utils\Grapher\Graphite::numericOid( $cat['oid_in'] ) ?>"
      name = "<?=$cat['token']?>.in"   # <?=$cat['mib_in']?>

    [[inputs.snmp.table.field]]
      oid  = "<?= \IXP\Utils\Grapher\Graphite::numericOid( $cat['oid_out'] ) ?>"
      name = "<?=$cat['token']?>.out"  # <?=$cat['mib_out']?>

<?php endforeach; ?>
<?php endforeach; ?>
